# coding: utf-8

"""
    KS Trade API's

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.todays import Todays  # noqa: E501
from openapi_client.rest import ApiException

class TestTodays(unittest.TestCase):
    """Todays unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Todays
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.todays.Todays()  # noqa: E501
        if include_optional :
            return Todays(
                instrumentToken = 56, 
                normal = 1.337, 
                supermultiple = 1.337, 
                mtf = 1.337, 
                actualNetTrdValue = 1.337, 
                averageStockPrice = 1.337, 
                buyOpenQtyLot = 56, 
                buyOpenVal = 1.337, 
                buyTradedQtyLot = 56, 
                buyTradedVal = 1.337, 
                buyTrdAvg = 1.337, 
                deliveryStatus = 56, 
                denominator = 56, 
                exchange = '0', 
                exposureMargin = 56, 
                exposureMarginTotal = 56, 
                grossUtilization = 1.337, 
                instrumentName = '0', 
                lastPrice = 1.337, 
                marginType = '0', 
                maxCODQty = 56, 
                multiplier = 56, 
                netTrdQtyLot = 56, 
                netTrdValue = 1.337, 
                normalSqOffQty = 1.337, 
                premium = 1.337, 
                rbiRefRate = 56, 
                realizedPL = 1.337, 
                sellOpenQtyLot = 56, 
                sellOpenVal = 56, 
                sellTradedQtyLot = 56, 
                sellTradedVal = 56, 
                sellTrdAvg = 1.337, 
                spanMargin = 56, 
                spanMarginTotal = 1.337, 
                spreadTotal = 1.337, 
                totalStock = 56
            )
        else :
            return Todays(
        )

    def testTodays(self):
        """Test Todays"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
